apiVersion: v1
kind: Pod
metadata:
  name: l2c-trigger-demo
  labels:
    app: l2c-trigger-demo
spec:
  serviceAccountName: l2c-account
  containers:
  - name: l2c-trigger-demo
    image: azssi/l2c-trigger:v0.0.1
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: l2c-trigger-demo
spec:
  type: LoadBalancer
  ports:
  - port: 13000
    targetPort: 13000
  selector:
    app: l2c-trigger-demo